development:
  password: shptka_df2d49618f33228ef02a14876ce078be
  theme_id: "133368447199"
  store: crazybulk-demo-2.myshopify.com
  ignore_files:
  - '*.gif'
  - '*.jpg'
  - config/settings_data.json
